title: "Cerita Dewasa 2025"
email: "your-email@example.com"
description: >
  Baca Kumpulan Cerita Dewasa 2025 Menarik Dan Bikin Tegang Cerita Ini.

baseurl: "" # jangan dikasih slash
url: "https://kisahcandu.github.io"

permalink: "/:title/"

# Sosial Media
twitter_username: ""
github_username: "Bang Sugeng"

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Build
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  

# File dan folder yang tidak perlu diproses
exclude:
  - README.md
  - node_modules
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json
