name: Generate Jekyll Posts from WordPress

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create empty published_posts.json if it doesn't exist
        run: |
          touch published_posts.json # Buat file kosong jika belum ada
        # Tambahkan kondisi jika Anda ingin lebih ketat:
        # if: steps.checkout.outputs.file-exists == 'false' # Ini akan membutuhkan output dari langkah checkout, agak lebih kompleks
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download NLTK punkt tokenizer
        run: |
          python -c "import nltk; nltk.download('punkt')"

      - name: Run Python script to generate Jekyll posts
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WORDPRESS_BLOG_ID: ${{ secrets.WORDPRESS_BLOG_ID }}
        run: |
          python wordpress_importer.py

      - name: Commit and push generated _posts and state file
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add _posts/
          git add published_posts.json
          git commit -m "Generate and update Jekyll posts from WordPress" || true
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
